name: firebase_image
description: A cached Flutter ImageProvider for Firebase Cloud Storage image objects.
version: 1.1.1
homepage: https://github.com/mattreid1/firebase_image

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.7.0
  firebase_storage: ^11.0.14
  path_provider: ^2.0.13
  path: ^1.8.2
  sqflite: ^2.2.5

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
